services:
  api_mock_app:
    build:
      context: .
      cache_from:
        - nimblehq/api-mock-app:latest
    image: nimblehq/api-mock-app:latest
    container_name: api_mock_app
    volumes:
      - ./docs:/api_mock/docs
    ports:
      - "4010:4010"
